//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.12.20 at 10:57:58 PM EST
//


package com.whirlpool.frauddetectionservice.order.response;

import javax.xml.bind.annotation.*;


/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transaction-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cross-reference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rules-tripped" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="total-score" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="recommendation-code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{ "transactionId", "crossReference", "rulesTripped", "totalScore", "recommendationCode", "remarks" })
@XmlRootElement(name = "transaction-results")
public class TransactionResults
{

	@XmlElement(name = "transaction-id", required = true)
	protected String transactionId;
	@XmlElement(name = "cross-reference", required = true)
	protected String crossReference;
	@XmlElement(name = "rules-tripped", required = true)
	protected String rulesTripped;
	@XmlElement(name = "total-score", required = true)
	protected String totalScore;
	@XmlElement(name = "recommendation-code", required = true)
	protected String recommendationCode;
	@XmlElement(required = true)
	protected String remarks;

	/**
	 * Gets the value of the transactionId property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTransactionId()
	{
		return transactionId;
	}

	/**
	 * Sets the value of the transactionId property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setTransactionId(final String value)
	{
		this.transactionId = value;
	}

	/**
	 * Gets the value of the crossReference property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCrossReference()
	{
		return crossReference;
	}

	/**
	 * Sets the value of the crossReference property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setCrossReference(final String value)
	{
		this.crossReference = value;
	}

	/**
	 * Gets the value of the rulesTripped property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getRulesTripped()
	{
		return rulesTripped;
	}

	/**
	 * Sets the value of the rulesTripped property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setRulesTripped(final String value)
	{
		this.rulesTripped = value;
	}

	/**
	 * Gets the value of the totalScore property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTotalScore()
	{
		return totalScore;
	}

	/**
	 * Sets the value of the totalScore property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setTotalScore(final String value)
	{
		this.totalScore = value;
	}

	/**
	 * Gets the value of the recommendationCode property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getRecommendationCode()
	{
		return recommendationCode;
	}

	/**
	 * Sets the value of the recommendationCode property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setRecommendationCode(final String value)
	{
		this.recommendationCode = value;
	}

	/**
	 * Gets the value of the remarks property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getRemarks()
	{
		return remarks;
	}

	/**
	 * Sets the value of the remarks property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setRemarks(final String value)
	{
		this.remarks = value;
	}

}
