//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.12.20 at 10:54:59 PM EST
//


package com.whirlpool.frauddetectionservice.order.request;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 *
 */
@XmlRegistry
public class ObjectFactory
{


	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
	 *
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link TransactionRequest }
	 *
	 */
	public TransactionRequest createTransactionRequest()
	{
		return new TransactionRequest();
	}

	/**
	 * Create an instance of {@link TransactionRequest.OrderDetailInformation }
	 *
	 */
	public TransactionRequest.OrderDetailInformation createTransactionRequestOrderDetailInformation()
	{
		return new TransactionRequest.OrderDetailInformation();
	}

	/**
	 * Create an instance of {@link TransactionRequest.PaymentDetailInformation }
	 *
	 */
	public TransactionRequest.PaymentDetailInformation createTransactionRequestPaymentDetailInformation()
	{
		return new TransactionRequest.PaymentDetailInformation();
	}

	/**
	 * Create an instance of {@link TransactionRequest.OrderInformation }
	 *
	 */
	public TransactionRequest.OrderInformation createTransactionRequestOrderInformation()
	{
		return new TransactionRequest.OrderInformation();
	}

	/**
	 * Create an instance of {@link TransactionRequest.BillingInformation }
	 *
	 */
	public TransactionRequest.BillingInformation createTransactionRequestBillingInformation()
	{
		return new TransactionRequest.BillingInformation();
	}

	/**
	 * Create an instance of {@link TransactionRequest.MemberInformation }
	 *
	 */
	public TransactionRequest.MemberInformation createTransactionRequestMemberInformation()
	{
		return new TransactionRequest.MemberInformation();
	}

	/**
	 * Create an instance of {@link TransactionRequest.ShippingInformation }
	 *
	 */
	public TransactionRequest.ShippingInformation createTransactionRequestShippingInformation()
	{
		return new TransactionRequest.ShippingInformation();
	}

	/**
	 * Create an instance of {@link TransactionRequest.OrderDetailInformation.OrderItem }
	 *
	 */
	public TransactionRequest.OrderDetailInformation.OrderItem createTransactionRequestOrderDetailInformationOrderItem()
	{
		return new TransactionRequest.OrderDetailInformation.OrderItem();
	}

	/**
	 * Create an instance of {@link TransactionRequest.PaymentDetailInformation.PaymentSource }
	 *
	 */
	public TransactionRequest.PaymentDetailInformation.PaymentSource createTransactionRequestPaymentDetailInformationPaymentSource()
	{
		return new TransactionRequest.PaymentDetailInformation.PaymentSource();
	}

}
