//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.12.20 at 10:54:59 PM EST
//


package com.whirlpool.frauddetectionservice.order.request;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="orderInformation"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="transactionID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="store" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="orderDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="orderTotalTax" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="orderTotalShipping" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="orderTotalAmount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="orderCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="orderIpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="iovationBlackBox" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BillingInformation"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="billingFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingMiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingAddress3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingCity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingPostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingCountry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingPhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="billingMobilePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="memberInformation"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="memberID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="membershipDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="shippingInformation"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="shippingFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingMiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingAddress3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingCity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingPostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingCountry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="shippingPhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="paymentDetailInformation"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="paymentSource"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="paymentCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="paymentCreditCardFullName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="paymentCardType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="paymentCardExpireDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="paymentCardBilledAmount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="orderDetailInformation"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="orderItem" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="itemNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="itemDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="itemQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="itemPrice" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="itemCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="itemColor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="shippingMethod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="itemGiftWrapMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlRootElement(name = "transactionRequest")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{ "orderInformation", "billingInformation", "memberInformation", "shippingInformation", "paymentDetailInformation",
		"orderDetailInformation" })
public class TransactionRequest
{

	@XmlElement(required = true)
	protected TransactionRequest.OrderInformation orderInformation;
	@XmlElement(name = "BillingInformation", required = true)
	protected TransactionRequest.BillingInformation billingInformation;
	@XmlElement(required = true)
	protected TransactionRequest.MemberInformation memberInformation;
	@XmlElement(required = true)
	protected TransactionRequest.ShippingInformation shippingInformation;
	@XmlElement(required = true)
	protected TransactionRequest.PaymentDetailInformation paymentDetailInformation;
	@XmlElement(required = true)
	protected TransactionRequest.OrderDetailInformation orderDetailInformation;

	/**
	 * Gets the value of the orderInformation property.
	 *
	 * @return possible object is {@link OrderInformation }
	 *
	 */
	public OrderInformation getOrderInformation()
	{
		return orderInformation;
	}

	/**
	 * Sets the value of the orderInformation property.
	 *
	 * @param value
	 *           allowed object is {@link OrderInformation }
	 *
	 */
	public void setOrderInformation(final OrderInformation value)
	{
		this.orderInformation = value;
	}

	/**
	 * Gets the value of the billingInformation property.
	 *
	 * @return possible object is {@link BillingInformation }
	 *
	 */
	public BillingInformation getBillingInformation()
	{
		return billingInformation;
	}

	/**
	 * Sets the value of the billingInformation property.
	 *
	 * @param value
	 *           allowed object is {@link BillingInformation }
	 *
	 */
	public void setBillingInformation(final BillingInformation value)
	{
		this.billingInformation = value;
	}

	/**
	 * Gets the value of the memberInformation property.
	 *
	 * @return possible object is {@link MemberInformation }
	 *
	 */
	public MemberInformation getMemberInformation()
	{
		return memberInformation;
	}

	/**
	 * Sets the value of the memberInformation property.
	 *
	 * @param value
	 *           allowed object is {@link MemberInformation }
	 *
	 */
	public void setMemberInformation(final MemberInformation value)
	{
		this.memberInformation = value;
	}

	/**
	 * Gets the value of the shippingInformation property.
	 *
	 * @return possible object is {@link ShippingInformation }
	 *
	 */
	public ShippingInformation getShippingInformation()
	{
		return shippingInformation;
	}

	/**
	 * Sets the value of the shippingInformation property.
	 *
	 * @param value
	 *           allowed object is {@link ShippingInformation }
	 *
	 */
	public void setShippingInformation(final ShippingInformation value)
	{
		this.shippingInformation = value;
	}

	/**
	 * Gets the value of the paymentDetailInformation property.
	 *
	 * @return possible object is {@link PaymentDetailInformation }
	 *
	 */
	public PaymentDetailInformation getPaymentDetailInformation()
	{
		return paymentDetailInformation;
	}

	/**
	 * Sets the value of the paymentDetailInformation property.
	 *
	 * @param value
	 *           allowed object is {@link PaymentDetailInformation }
	 *
	 */
	public void setPaymentDetailInformation(final PaymentDetailInformation value)
	{
		this.paymentDetailInformation = value;
	}

	/**
	 * Gets the value of the orderDetailInformation property.
	 *
	 * @return possible object is {@link OrderDetailInformation }
	 *
	 */
	public OrderDetailInformation getOrderDetailInformation()
	{
		return orderDetailInformation;
	}

	/**
	 * Sets the value of the orderDetailInformation property.
	 *
	 * @param value
	 *           allowed object is {@link OrderDetailInformation }
	 *
	 */
	public void setOrderDetailInformation(final OrderDetailInformation value)
	{
		this.orderDetailInformation = value;
	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="billingFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingMiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingAddress3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingCity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingPostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingCountry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingPhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="billingMobilePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "billingFirstName", "billingLastName", "billingMiddleName", "billingAddress", "billingAddress2", "billingAddress3",
			"billingCity", "billingRegion", "billingPostalCode", "billingCountry", "billingEmail", "billingPhone",
			"billingMobilePhone" })
	public static class BillingInformation
	{

		@XmlElement(required = true)
		protected String billingFirstName;
		@XmlElement(required = true)
		protected String billingLastName;
		@XmlElement(required = true)
		protected String billingMiddleName;
		@XmlElement(required = true)
		protected String billingAddress;
		@XmlElement(required = true)
		protected String billingAddress2;
		@XmlElement(required = true)
		protected String billingAddress3;
		@XmlElement(required = true)
		protected String billingCity;
		@XmlElement(required = true)
		protected String billingRegion;
		@XmlElement(required = true)
		protected String billingPostalCode;
		@XmlElement(required = true)
		protected String billingCountry;
		@XmlElement(required = true)
		protected String billingEmail;
		@XmlElement(required = true)
		protected String billingPhone;
		@XmlElement(required = true)
		protected String billingMobilePhone;

		/**
		 * Gets the value of the billingFirstName property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingFirstName()
		{
			return billingFirstName;
		}

		/**
		 * Sets the value of the billingFirstName property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingFirstName(final String value)
		{
			this.billingFirstName = value;
		}

		/**
		 * Gets the value of the billingLastName property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingLastName()
		{
			return billingLastName;
		}

		/**
		 * Sets the value of the billingLastName property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingLastName(final String value)
		{
			this.billingLastName = value;
		}

		/**
		 * Gets the value of the billingMiddleName property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingMiddleName()
		{
			return billingMiddleName;
		}

		/**
		 * Sets the value of the billingMiddleName property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingMiddleName(final String value)
		{
			this.billingMiddleName = value;
		}

		/**
		 * Gets the value of the billingAddress property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingAddress()
		{
			return billingAddress;
		}

		/**
		 * Sets the value of the billingAddress property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingAddress(final String value)
		{
			this.billingAddress = value;
		}

		/**
		 * Gets the value of the billingAddress2 property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingAddress2()
		{
			return billingAddress2;
		}

		/**
		 * Sets the value of the billingAddress2 property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingAddress2(final String value)
		{
			this.billingAddress2 = value;
		}

		/**
		 * Gets the value of the billingAddress3 property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingAddress3()
		{
			return billingAddress3;
		}

		/**
		 * Sets the value of the billingAddress3 property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingAddress3(final String value)
		{
			this.billingAddress3 = value;
		}

		/**
		 * Gets the value of the billingCity property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingCity()
		{
			return billingCity;
		}

		/**
		 * Sets the value of the billingCity property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingCity(final String value)
		{
			this.billingCity = value;
		}

		/**
		 * Gets the value of the billingRegion property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingRegion()
		{
			return billingRegion;
		}

		/**
		 * Sets the value of the billingRegion property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingRegion(final String value)
		{
			this.billingRegion = value;
		}

		/**
		 * Gets the value of the billingPostalCode property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingPostalCode()
		{
			return billingPostalCode;
		}

		/**
		 * Sets the value of the billingPostalCode property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingPostalCode(final String value)
		{
			this.billingPostalCode = value;
		}

		/**
		 * Gets the value of the billingCountry property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingCountry()
		{
			return billingCountry;
		}

		/**
		 * Sets the value of the billingCountry property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingCountry(final String value)
		{
			this.billingCountry = value;
		}

		/**
		 * Gets the value of the billingEmail property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingEmail()
		{
			return billingEmail;
		}

		/**
		 * Sets the value of the billingEmail property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingEmail(final String value)
		{
			this.billingEmail = value;
		}

		/**
		 * Gets the value of the billingPhone property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingPhone()
		{
			return billingPhone;
		}

		/**
		 * Sets the value of the billingPhone property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingPhone(final String value)
		{
			this.billingPhone = value;
		}

		/**
		 * Gets the value of the billingMobilePhone property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getBillingMobilePhone()
		{
			return billingMobilePhone;
		}

		/**
		 * Sets the value of the billingMobilePhone property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setBillingMobilePhone(final String value)
		{
			this.billingMobilePhone = value;
		}

	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="memberID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="membershipDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "memberID", "membershipDate" })
	public static class MemberInformation
	{

		@XmlElement(required = true)
		protected String memberID;
		@XmlElement(required = false)
		protected String membershipDate;

		/**
		 * Gets the value of the memberID property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getMemberID()
		{
			return memberID;
		}

		/**
		 * Sets the value of the memberID property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setMemberID(final String value)
		{
			this.memberID = value;
		}

		/**
		 * Gets the value of the membershipDate property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getMembershipDate()
		{
			return membershipDate;
		}

		/**
		 * Sets the value of the membershipDate property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setMembershipDate(final String value)
		{
			this.membershipDate = value;
		}

	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="orderItem" maxOccurs="unbounded" minOccurs="0"&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;sequence&gt;
	 *                   &lt;element name="itemNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="itemDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="itemQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="itemPrice" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="itemCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="itemColor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="shippingMethod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="itemGiftWrapMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                 &lt;/sequence&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "orderItem" })
	public static class OrderDetailInformation
	{

		protected List<OrderItem> orderItem;

		/**
		 * Gets the value of the orderItem property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
		 * orderItem property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getOrderItem().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link OrderItem }
		 *
		 *
		 */
		public List<OrderItem> getOrderItem()
		{
			if (orderItem == null)
			{
				orderItem = new ArrayList<OrderItem>();
			}
			return this.orderItem;
		}


		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;sequence&gt;
		 *         &lt;element name="itemNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="itemDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="itemQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="itemPrice" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="itemCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="itemColor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="shippingMethod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="itemGiftWrapMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *       &lt;/sequence&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder =
		{ "itemNumber", "itemDescription", "itemQuantity", "itemPrice", "itemCategory", "itemColor", "shippingMethod",
				"itemGiftWrapMessage" })
		public static class OrderItem
		{

			@XmlElement(required = true)
			protected String itemNumber;
			@XmlElement(required = true)
			protected String itemDescription;
			@XmlElement(required = true)
			protected String itemQuantity;
			@XmlElement(required = true)
			protected String itemPrice;
			@XmlElement(required = true)
			protected String itemCategory;
			@XmlElement(required = true)
			protected String itemColor;
			@XmlElement(required = true)
			protected String shippingMethod;
			@XmlElement(required = true)
			protected String itemGiftWrapMessage;

			/**
			 * Gets the value of the itemNumber property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getItemNumber()
			{
				return itemNumber;
			}

			/**
			 * Sets the value of the itemNumber property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setItemNumber(final String value)
			{
				this.itemNumber = value;
			}

			/**
			 * Gets the value of the itemDescription property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getItemDescription()
			{
				return itemDescription;
			}

			/**
			 * Sets the value of the itemDescription property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setItemDescription(final String value)
			{
				this.itemDescription = value;
			}

			/**
			 * Gets the value of the itemQuantity property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getItemQuantity()
			{
				return itemQuantity;
			}

			/**
			 * Sets the value of the itemQuantity property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setItemQuantity(final String value)
			{
				this.itemQuantity = value;
			}

			/**
			 * Gets the value of the itemPrice property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getItemPrice()
			{
				return itemPrice;
			}

			/**
			 * Sets the value of the itemPrice property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setItemPrice(final String value)
			{
				this.itemPrice = value;
			}

			/**
			 * Gets the value of the itemCategory property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getItemCategory()
			{
				return itemCategory;
			}

			/**
			 * Sets the value of the itemCategory property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setItemCategory(final String value)
			{
				this.itemCategory = value;
			}

			/**
			 * Gets the value of the itemColor property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getItemColor()
			{
				return itemColor;
			}

			/**
			 * Sets the value of the itemColor property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setItemColor(final String value)
			{
				this.itemColor = value;
			}

			/**
			 * Gets the value of the shippingMethod property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getShippingMethod()
			{
				return shippingMethod;
			}

			/**
			 * Sets the value of the shippingMethod property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setShippingMethod(final String value)
			{
				this.shippingMethod = value;
			}

			/**
			 * Gets the value of the itemGiftWrapMessage property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getItemGiftWrapMessage()
			{
				return itemGiftWrapMessage;
			}

			/**
			 * Sets the value of the itemGiftWrapMessage property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setItemGiftWrapMessage(final String value)
			{
				this.itemGiftWrapMessage = value;
			}

		}

	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="transactionID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="store" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="orderDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="orderTotalTax" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="orderTotalShipping" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="orderTotalAmount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="orderCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="orderIpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="iovationBlackBox" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "transactionID", "operation", "store", "orderDateTime", "orderTotalTax", "orderTotalShipping", "orderTotalAmount",
			"orderCurrencyCode", "orderIpAddress", "iovationBlackBox" })
	public static class OrderInformation
	{

		@XmlElement(required = true)
		protected String transactionID;
		@XmlElement(required = true)
		protected String operation;
		@XmlElement(required = true)
		protected String store;
		@XmlElement(required = true)
		protected String orderDateTime;
		@XmlElement(required = true)
		protected String orderTotalTax;
		@XmlElement(required = true)
		protected String orderTotalShipping;
		@XmlElement(required = true)
		protected String orderTotalAmount;
		@XmlElement(required = true)
		protected String orderCurrencyCode;
		@XmlElement(required = true)
		protected String orderIpAddress;
		@XmlElement(required = true)
		protected String iovationBlackBox;

		/**
		 * Gets the value of the transactionID property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getTransactionID()
		{
			return transactionID;
		}

		/**
		 * Sets the value of the transactionID property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setTransactionID(final String value)
		{
			this.transactionID = value;
		}

		/**
		 * Gets the value of the operation property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getOperation()
		{
			return operation;
		}

		/**
		 * Sets the value of the operation property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setOperation(final String value)
		{
			this.operation = value;
		}

		/**
		 * Gets the value of the store property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getStore()
		{
			return store;
		}

		/**
		 * Sets the value of the store property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setStore(final String value)
		{
			this.store = value;
		}

		/**
		 * Gets the value of the orderDateTime property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getOrderDateTime()
		{
			return orderDateTime;
		}

		/**
		 * Sets the value of the orderDateTime property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setOrderDateTime(final String value)
		{
			this.orderDateTime = value;
		}

		/**
		 * Gets the value of the orderTotalTax property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getOrderTotalTax()
		{
			return orderTotalTax;
		}

		/**
		 * Sets the value of the orderTotalTax property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setOrderTotalTax(final String value)
		{
			this.orderTotalTax = value;
		}

		/**
		 * Gets the value of the orderTotalShipping property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getOrderTotalShipping()
		{
			return orderTotalShipping;
		}

		/**
		 * Sets the value of the orderTotalShipping property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setOrderTotalShipping(final String value)
		{
			this.orderTotalShipping = value;
		}

		/**
		 * Gets the value of the orderTotalAmount property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getOrderTotalAmount()
		{
			return orderTotalAmount;
		}

		/**
		 * Sets the value of the orderTotalAmount property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setOrderTotalAmount(final String value)
		{
			this.orderTotalAmount = value;
		}

		/**
		 * Gets the value of the orderCurrencyCode property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getOrderCurrencyCode()
		{
			return orderCurrencyCode;
		}

		/**
		 * Sets the value of the orderCurrencyCode property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setOrderCurrencyCode(final String value)
		{
			this.orderCurrencyCode = value;
		}

		/**
		 * Gets the value of the orderIpAddress property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getOrderIpAddress()
		{
			return orderIpAddress;
		}

		/**
		 * Sets the value of the orderIpAddress property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setOrderIpAddress(final String value)
		{
			this.orderIpAddress = value;
		}

		/**
		 * Gets the value of the iovationBlackBox property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getIovationBlackBox()
		{
			return iovationBlackBox;
		}

		/**
		 * Sets the value of the iovationBlackBox property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setIovationBlackBox(final String value)
		{
			this.iovationBlackBox = value;
		}

	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="paymentSource"&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;sequence&gt;
	 *                   &lt;element name="paymentCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="paymentCreditCardFullName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="paymentCardType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="paymentCardExpireDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="paymentCardBilledAmount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                 &lt;/sequence&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "paymentSource" })
	public static class PaymentDetailInformation
	{

		@XmlElement(required = true)
		protected TransactionRequest.PaymentDetailInformation.PaymentSource paymentSource;

		/**
		 * Gets the value of the paymentSource property.
		 *
		 * @return possible object is {@link PaymentSource }
		 *
		 */
		public PaymentSource getPaymentSource()
		{
			return paymentSource;
		}

		/**
		 * Sets the value of the paymentSource property.
		 *
		 * @param value
		 *           allowed object is {@link PaymentSource }
		 *
		 */
		public void setPaymentSource(final PaymentSource value)
		{
			this.paymentSource = value;
		}


		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;sequence&gt;
		 *         &lt;element name="paymentCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="paymentCreditCardFullName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="paymentCardType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="paymentCardExpireDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="paymentCardBilledAmount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *       &lt;/sequence&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder =
		{ "paymentCardNumber", "paymentCreditCardFullName", "paymentCardType", "paymentCardExpireDate", "paymentCardBilledAmount" })
		public static class PaymentSource
		{

			@XmlElement(required = true)
			protected String paymentCardNumber;
			@XmlElement(required = true)
			protected String paymentCreditCardFullName;
			@XmlElement(required = true)
			protected String paymentCardType;
			@XmlElement(required = true)
			protected String paymentCardExpireDate;
			@XmlElement(required = true)
			protected String paymentCardBilledAmount;

			/**
			 * Gets the value of the paymentCardNumber property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getPaymentCardNumber()
			{
				return paymentCardNumber;
			}

			/**
			 * Sets the value of the paymentCardNumber property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setPaymentCardNumber(final String value)
			{
				this.paymentCardNumber = value;
			}

			/**
			 * Gets the value of the paymentCreditCardFullName property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getPaymentCreditCardFullName()
			{
				return paymentCreditCardFullName;
			}

			/**
			 * Sets the value of the paymentCreditCardFullName property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setPaymentCreditCardFullName(final String value)
			{
				this.paymentCreditCardFullName = value;
			}

			/**
			 * Gets the value of the paymentCardType property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getPaymentCardType()
			{
				return paymentCardType;
			}

			/**
			 * Sets the value of the paymentCardType property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setPaymentCardType(final String value)
			{
				this.paymentCardType = value;
			}

			/**
			 * Gets the value of the paymentCardExpireDate property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getPaymentCardExpireDate()
			{
				return paymentCardExpireDate;
			}

			/**
			 * Sets the value of the paymentCardExpireDate property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setPaymentCardExpireDate(final String value)
			{
				this.paymentCardExpireDate = value;
			}

			/**
			 * Gets the value of the paymentCardBilledAmount property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getPaymentCardBilledAmount()
			{
				return paymentCardBilledAmount;
			}

			/**
			 * Sets the value of the paymentCardBilledAmount property.
			 *
			 * @param value
			 *           allowed object is {@link String }
			 *
			 */
			public void setPaymentCardBilledAmount(final String value)
			{
				this.paymentCardBilledAmount = value;
			}

		}

	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="shippingFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingMiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingAddress3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingCity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingPostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingCountry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *         &lt;element name="shippingPhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder =
	{ "shippingFirstName", "shippingMiddleName", "shippingLastName", "shippingAddress", "shippingAddress2", "shippingAddress3",
			"shippingCity", "shippingRegion", "shippingPostalCode", "shippingCountry", "shippingEmail", "shippingPhone" })
	public static class ShippingInformation
	{

		@XmlElement(required = true)
		protected String shippingFirstName;
		@XmlElement(required = true)
		protected String shippingMiddleName;
		@XmlElement(required = true)
		protected String shippingLastName;
		@XmlElement(required = true)
		protected String shippingAddress;
		@XmlElement(required = true)
		protected String shippingAddress2;
		@XmlElement(required = true)
		protected String shippingAddress3;
		@XmlElement(required = true)
		protected String shippingCity;
		@XmlElement(required = true)
		protected String shippingRegion;
		@XmlElement(required = true)
		protected String shippingPostalCode;
		@XmlElement(required = true)
		protected String shippingCountry;
		@XmlElement(required = true)
		protected String shippingEmail;
		@XmlElement(required = true)
		protected String shippingPhone;

		/**
		 * Gets the value of the shippingFirstName property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingFirstName()
		{
			return shippingFirstName;
		}

		/**
		 * Sets the value of the shippingFirstName property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingFirstName(final String value)
		{
			this.shippingFirstName = value;
		}

		/**
		 * Gets the value of the shippingMiddleName property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingMiddleName()
		{
			return shippingMiddleName;
		}

		/**
		 * Sets the value of the shippingMiddleName property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingMiddleName(final String value)
		{
			this.shippingMiddleName = value;
		}

		/**
		 * Gets the value of the shippingLastName property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingLastName()
		{
			return shippingLastName;
		}

		/**
		 * Sets the value of the shippingLastName property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingLastName(final String value)
		{
			this.shippingLastName = value;
		}

		/**
		 * Gets the value of the shippingAddress property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingAddress()
		{
			return shippingAddress;
		}

		/**
		 * Sets the value of the shippingAddress property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingAddress(final String value)
		{
			this.shippingAddress = value;
		}

		/**
		 * Gets the value of the shippingAddress2 property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingAddress2()
		{
			return shippingAddress2;
		}

		/**
		 * Sets the value of the shippingAddress2 property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingAddress2(final String value)
		{
			this.shippingAddress2 = value;
		}

		/**
		 * Gets the value of the shippingAddress3 property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingAddress3()
		{
			return shippingAddress3;
		}

		/**
		 * Sets the value of the shippingAddress3 property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingAddress3(final String value)
		{
			this.shippingAddress3 = value;
		}

		/**
		 * Gets the value of the shippingCity property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingCity()
		{
			return shippingCity;
		}

		/**
		 * Sets the value of the shippingCity property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingCity(final String value)
		{
			this.shippingCity = value;
		}

		/**
		 * Gets the value of the shippingRegion property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingRegion()
		{
			return shippingRegion;
		}

		/**
		 * Sets the value of the shippingRegion property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingRegion(final String value)
		{
			this.shippingRegion = value;
		}

		/**
		 * Gets the value of the shippingPostalCode property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingPostalCode()
		{
			return shippingPostalCode;
		}

		/**
		 * Sets the value of the shippingPostalCode property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingPostalCode(final String value)
		{
			this.shippingPostalCode = value;
		}

		/**
		 * Gets the value of the shippingCountry property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingCountry()
		{
			return shippingCountry;
		}

		/**
		 * Sets the value of the shippingCountry property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingCountry(final String value)
		{
			this.shippingCountry = value;
		}

		/**
		 * Gets the value of the shippingEmail property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingEmail()
		{
			return shippingEmail;
		}

		/**
		 * Sets the value of the shippingEmail property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingEmail(final String value)
		{
			this.shippingEmail = value;
		}

		/**
		 * Gets the value of the shippingPhone property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getShippingPhone()
		{
			return shippingPhone;
		}

		/**
		 * Sets the value of the shippingPhone property.
		 *
		 * @param value
		 *           allowed object is {@link String }
		 *
		 */
		public void setShippingPhone(final String value)
		{
			this.shippingPhone = value;
		}

	}

}
