server:
  port: 8701

spring:
  cloud:
    kubernetes:
      config:
        name: frauddetection-service
        namespace: whirlpool

management:
  endpoints:
    web:
      exposure:
        include: "*"



accertify:
  password:
    whirlpool-us: Password2345@
  preauth:
    endpoint:
      url:
        whirlpool-us: https://icnow01.accertify.net/icNowImport/61505eb9-1bd5-490a-b1af-f142de2c8dfe
  user:
    whirlpool-us: whirlpool_us_qa_import
